codecov:
  require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        base: auto
        # advanced
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false